name: Clojure CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-java@v1
      with:
        java-version: '9'

    - name: Cache maven
      uses: actions/cache@v2
      env:
          cache-name: cache-maven
      with:
          path: ~/.m2
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/project.clj') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/project.clj') }}

    - name: Install dependencies
      run: lein deps

    - name: Run Clojure tests
      run: lein test
